# Generated by Django 4.1 on 2023-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitranscript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='transcript',
            field=models.TextField(default=''),
        ),
    ]
