# Generated by Django 4.1 on 2023-12-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aitranscript', '0003_user_pasword_alter_inputfile_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
    ]
