# Generated by Django 4.1 on 2023-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitranscript', '0004_rename_pasword_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='summary_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputfile',
            name='transcript_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputfile',
            name='upload_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='status',
            field=models.CharField(choices=[('UP', 'Uploaded'), ('PR', 'Em processamento'), ('TR', 'Transcrito'), ('RE', 'Resumido'), ('FT', 'Falha na transcrição'), ('FR', 'Falha no resumo')], default='UP', max_length=2),
        ),
    ]
