# Generated by Django 4.1 on 2023-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitranscript', '0005_inputfile_summary_dt_inputfile_transcript_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='file_key',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
