# Generated by Django 4.1 on 2024-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitranscript', '0006_inputfile_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='lock_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
